// <auto-generated />
namespace GroupCapstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedmoreinfoontoexistingtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedmoreinfoontoexistingtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201802122047200_added more info onto existing table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
